network:
  name: "Texas2k_case1_2016summerpeak" # Name of the power grid network
  source: "file" # Data source for the grid; options: pglib, pandapower, file

load:
  generator: "casefile" # Name of the load generator
  scenarios: 1 # Number of different load scenarios to generate

topology_perturbation:
  type: "from_list_of_bus_pairs" # Type of topology generator; options: n_minus_k, random, overloaded, none, from_list_of_bus_pairs
  line_bus_pairs_csv_path: "scripts/affected_line_nodes/affected_line_nodes_ike-wc.csv"
  

settings:
  num_processes: 10 # Number of parallel processes to use
  data_dir: "../data_contingency" # Directory to save generated data
  no_stats: false # If true, disables statistical calculations
  overwrite: true # If true, overwrites existing files
  mode: "contingency" # Mode of the script; options: contingency, pf


