#!/bin/bash

set -e

BASE="/dccstor/gridfm/powermodels_data/v4/finetuning/pf"

grids=(
#   case14_ieee
#   case30_ieee
#   case57_ieee
#   case118_ieee
#   case500_goc
#   case1354_pegase
#   case2000_goc
  case10000_goc
)

# grids=(
#   case240_pserc
#   case24_ieee_rts
#   case39_epri
#   case60_c
#   case73_ieee_rts
#   case162_ieee_dtc
#   case179_goc
#   case197_snem
#   case200_activ
#   case300_ieee
# )

source /u/apu/gridfm-datakit/venv/bin/activate


for g in "${grids[@]}"; do
    # echo "Validating $g..."

    # if [[ ! -e "$BASE/$g/raw/0_GEN_COSTS_OK" ]]; then
    #     echo "❌ Missing 0_GEN_COSTS_OK for $g"
    #     exit 1
    # fi

    gridfm_datakit validate  "$BASE/$g/raw" --n-partitions 50 --mode pf
    if [[ $? -ne 0 ]]; then
        echo "❌ Validation failed for $g"
        exit 1   # uncomment to stop on first failure
        continue   # continue to next grid
    else
        echo "✅ Validation OK for $g"
        touch "$BASE/$g/raw/0_VALIDATION_OK"
    fi

    echo "Stats $g..."
    gridfm_datakit stats "$BASE/$g/raw"
    gridfm_datakit plots "$BASE/$g/raw"
done
echo "All validations completed."
# touch "$BASE/0_VALIDATION_OK"