network:
  name: "case39_epri" # Name of the power grid network (without extension)
  source: "pglib" # Data source for the grid; options: pglib, pandapower, file
  network_dir: "scripts/grids" # if using source "file", this is the directory containing the network file (relative to the project root)

load:
  generator: "agg_load_profile" # Name of the load generator; options: agg_load_profile, powergraph
  agg_profile: "default" # Name of the aggregated load profile
  scenarios: 10000 # Number of different load scenarios to generate
  # WARNING: the following parameters are only used if generator is "agg_load_profile"
  # if using generator "powergraph", these parameters are ignored
  sigma: 0.2 # max local noise
  change_reactive_power: true # If true, changes reactive power of loads. If False, keeps the ones from the case file
  global_range: 0.4 # Range of the global scaling factor. used to set the lower bound of the scaling factor
  max_scaling_factor: 4.0 # Max upper bound of the global scaling factor
  step_size: 0.025 # Step size when finding the upper bound of the global scaling factor
  start_scaling_factor: 0.8 # Initial value of the global scaling factor
  find_limit: false # If set to true, will run opf with pandapower run OPF to find upper limit. Set to false if using Julia to run OPF
  upper_limit: 1.2 # Upper limit for load profile

topology_perturbation:
  type: "random" # Type of topology generator; options: n_minus_k, random, none
  # WARNING: the following parameters are only used if type is not "none"
  k: 2 # Maximum number of components to drop in each perturbation
  n_topology_variants: 10 # Number of unique perturbed topologies per scenario
  elements: ["line", "trafo"] # elements to perturb options: line, trafo, gen, sgen

generation_perturbation:
  type: "cost_permutation" # Type of generation perturbation; options: cost_permutation, cost_perturbation, none
  sigma: 1.0 # Size of range use for sampling scaling factor

admittance_perturbation:
  type: "random_perturbation" # Type of admittance perturbation; options: random_perturbation, none
  sigma: 0.2 # Size of range used for sampling scaling factor

settings:
  num_processes: 10 # Number of parallel processes to use
  data_dir: "./data_out/" # Directory to save generated data relative to the project root
  large_chunk_size: 100 # Number of load scenarios processed before saving
  no_stats: false # If true, disables statistical calculations
  overwrite: true # If true, overwrites existing files, if false, appends to files
  mode: "unsecure" # Mode of the script; options: secure, unsecure. Unsecure mode generates unsecure scenarios, i.e. scenarios where the the generator setpoints are obtained for the base topology, before the topology is perturbed.
  dcpf: false # If true, also stores the results of dc power flow (in addition to the results AC power flow)
  julia: true # If true, uses Julia PowerModels to run OPF. If false, uses PandaPower OPF function.
  pm_solver: "ipopt" # Ipopt solver as default; update for ma27, ma57. Will be updated to pp.runpm_ac_opf(net, pm_log_level=5, pm_solver=pm_solver) if julia: true in solvers.py
